version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev-sample
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev-sample
  redis:
    image: redis:alpine
  celery:
    build: ./app
    command: celery -A core worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev-sample
    depends_on:
      - redis
  celery-beat:
    build: ./app
    command: celery -A core beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev-sample
    depends_on:
      - redis

volumes:
  postgres_data:
